apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  isso.cfg: |
    [general]
    dbpath = /db/comments.db
    host = https://eiersaft.me
